stages:
  data_ingestion:
    cmd: python src/data/data_ingestion.py
    deps:
    - src/data/data_ingestion.py
    params:
    - data_ingestion.test_size
    outs:
    - data/raw

  data_preprocessing:
    cmd: python src/data/data_preprocessing.py
    deps:
    - data/raw/train.csv
    - data/raw/test.csv
    - src/data/data_preprocessing.py
    outs:
    - data/interim

  feature_building:
    cmd: python src/features/feature_building.py
    deps:
    - data/interim/train_processed.csv
    - data/interim/test_processed.csv
    - src/features/feature_building.py
    params:
    - feature_building.max_features
    - feature_building.ngram_range
    outs:
    - tfidf_vectorizer.pkl

  model_building:
    cmd: python src/model/model_building.py
    deps:
    - tfidf_vectorizer.pkl
    - data/interim/train_processed.csv
    - src/features/feature_building.py
    - src/model/model_building.py
    params:
    - model_building.learning_rate
    - model_building.max_depth
    - model_building.n_estimators
    outs:
    - lgbm_model.pkl

  model_evaluation:
    cmd: python src/model/model_evaluation.py
    deps:
    - lgbm_model.pkl
    - tfidf_vectorizer.pkl
    - data/interim/train_processed.csv
    - data/interim/test_processed.csv
    - src/model/model_evaluation.py
    outs:
    - experiment_info.json

  model_registration:
    cmd: python src/model/register_model.py
    deps:
    - experiment_info.json
    - src/model/register_model.py