stages:
  data_ingestion:
    cmd: python src/data/data_ingestion.py
    deps:
    - src/data/data_ingestion.py
    params:
    - data_ingestion.test_size
    outs:
    - data/raw

  data_preprocessing:
    cmd: python src/data/data_preprocessing.py
    deps:
    - data/raw/train.csv
    - data/raw/test.csv
    - src/data/data_preprocessing.py
    outs:
    - data/interim

  feature_building:
    cmd: python src/features/feature_building.py
    deps:
    - data/interim/train_processed.csv
    - data/interim/test_processed.csv
    - src/features/feature_building.py
    params:
    - feature_building.max_features
    - feature_building.ngram_range
    outs:
    - tfidf_vectorizer.pkl